import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local"

const sequelFont = localFont({
   src: [
      {
         path: "./fonts/Sequel-Sans-Medium-Body.ttf",
         weight: "500",
         style: "normal",
      },
      {
         path: "./fonts/Sequel-Sans-Heavy-Body.ttf",
         weight: "600",
         style: "normal",
      },
      {
         path: "./fonts/Sequel-Sans-Black-Body.ttf",
         weight: "700",
         style: "normal",
      }
   ],
});


export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${sequelFont.className} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
